# Generated by Django 3.1.5 on 2021-01-19 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='created_at',
            new_name='created_date',
        ),
    ]
